@HOST=localhost
@PORT=9900
@API_PREFIX=api/v1
@ENDPOINT=customers

### Create Customer
POST http://{{HOST}}:{{PORT}}/{{API_PREFIX}}/{{ENDPOINT}}
Content-Type: application/json
  
{}

### Fetch all Customers
GET http://{{HOST}}:{{PORT}}/{{API_PREFIX}}/{{ENDPOINT}}
Content-Type: application/json